[2023-12-14T23:08:16.040+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2023-12-14T17:54:20.986043+00:00 [queued]>
[2023-12-14T23:08:16.061+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2023-12-14T17:54:20.986043+00:00 [queued]>
[2023-12-14T23:08:16.062+0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-14T23:08:16.102+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_model> on 2023-12-14 17:54:20.986043+00:00
[2023-12-14T23:08:16.113+0500] {standard_task_runner.py:57} INFO - Started process 42236 to run task
[2023-12-14T23:08:16.120+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'train_model', 'manual__2023-12-14T17:54:20.986043+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpdaplerjb']
[2023-12-14T23:08:16.123+0500] {standard_task_runner.py:85} INFO - Job 92: Subtask train_model
[2023-12-14T23:08:16.389+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.train_model manual__2023-12-14T17:54:20.986043+00:00 [running]> on host ml-vb
[2023-12-14T23:08:16.854+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2023-12-14T17:54:20.986043+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-14T17:54:20.986043+00:00'
[2023-12-14T23:08:16.858+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-14T23:08:16.859+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/ml/project/flow/scripts/train_model.py']
[2023-12-14T23:08:16.883+0500] {subprocess.py:86} INFO - Output:
[2023-12-14T23:08:39.067+0500] {subprocess.py:93} INFO - Registered model 'lr' already exists. Creating a new version of this model...
[2023-12-14T23:08:39.187+0500] {subprocess.py:93} INFO - 2023/12/14 23:08:39 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lr, version 19
[2023-12-14T23:08:39.206+0500] {subprocess.py:93} INFO - Created version '19' of model 'lr'.
[2023-12-14T23:08:39.211+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-14T23:08:39.211+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/scripts/train_model.py", line 27, in <module>
[2023-12-14T23:08:39.211+0500] {subprocess.py:93} INFO -     model.fit(X.values, y.values)
[2023-12-14T23:08:39.211+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/env/lib/python3.8/site-packages/sklearn/base.py", line 1152, in wrapper
[2023-12-14T23:08:39.212+0500] {subprocess.py:93} INFO -     return fit_method(estimator, *args, **kwargs)
[2023-12-14T23:08:39.212+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/env/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 348, in fit
[2023-12-14T23:08:39.212+0500] {subprocess.py:93} INFO -     X, y = self._validate_data(
[2023-12-14T23:08:39.212+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/env/lib/python3.8/site-packages/sklearn/base.py", line 622, in _validate_data
[2023-12-14T23:08:39.213+0500] {subprocess.py:93} INFO -     X, y = check_X_y(X, y, **check_params)
[2023-12-14T23:08:39.213+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/env/lib/python3.8/site-packages/sklearn/utils/validation.py", line 1146, in check_X_y
[2023-12-14T23:08:39.213+0500] {subprocess.py:93} INFO -     X = check_array(
[2023-12-14T23:08:39.213+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/env/lib/python3.8/site-packages/sklearn/utils/validation.py", line 967, in check_array
[2023-12-14T23:08:39.213+0500] {subprocess.py:93} INFO -     raise ValueError(
[2023-12-14T23:08:39.214+0500] {subprocess.py:93} INFO - ValueError: Found array with 0 sample(s) (shape=(0, 5)) while a minimum of 1 is required by RandomForestRegressor.
[2023-12-14T23:08:39.857+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-14T23:08:39.957+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ml/project/flow/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-14T23:08:39.968+0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=youtube_comments_score, task_id=train_model, execution_date=20231214T175420, start_date=20231214T180816, end_date=20231214T180839
[2023-12-14T23:08:40.011+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 92 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 42236)
[2023-12-14T23:08:40.065+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-14T23:08:40.211+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
