[2023-12-13T23:05:55.310+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2023-12-13T18:05:47.230503+00:00 [queued]>
[2023-12-13T23:05:55.325+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2023-12-13T18:05:47.230503+00:00 [queued]>
[2023-12-13T23:05:55.326+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-13T23:05:55.360+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): get_data> on 2023-12-13 18:05:47.230503+00:00
[2023-12-13T23:05:55.368+0500] {standard_task_runner.py:57} INFO - Started process 73964 to run task
[2023-12-13T23:05:55.374+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'manual__2023-12-13T18:05:47.230503+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpp51_wcme']
[2023-12-13T23:05:55.377+0500] {standard_task_runner.py:85} INFO - Job 3: Subtask get_data
[2023-12-13T23:05:55.767+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.get_data manual__2023-12-13T18:05:47.230503+00:00 [running]> on host ml-vb
[2023-12-13T23:05:56.301+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-13T18:05:47.230503+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-13T18:05:47.230503+00:00'
[2023-12-13T23:05:56.304+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-13T23:05:56.327+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/akashy/staidg/scripts/get_data.py']
[2023-12-13T23:05:56.365+0500] {subprocess.py:86} INFO - Output:
[2023-12-13T23:05:56.478+0500] {subprocess.py:93} INFO - python3: can't open file '/home/akashy/staidg/scripts/get_data.py': [Errno 2] No such file or directory
[2023-12-13T23:05:56.486+0500] {subprocess.py:97} INFO - Command exited with return code 2
[2023-12-13T23:05:56.566+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ml/project/flow/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-12-13T23:05:56.583+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=get_data, execution_date=20231213T180547, start_date=20231213T180555, end_date=20231213T180556
[2023-12-13T23:05:56.708+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task get_data (Bash command failed. The command returned a non-zero exit code 2.; 73964)
[2023-12-13T23:05:56.726+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-13T23:05:56.837+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
