[2023-12-13T23:11:04.760+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2023-12-13T18:05:47.230503+00:00 [queued]>
[2023-12-13T23:11:04.775+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2023-12-13T18:05:47.230503+00:00 [queued]>
[2023-12-13T23:11:04.775+0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-13T23:11:04.803+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): get_data> on 2023-12-13 18:05:47.230503+00:00
[2023-12-13T23:11:04.812+0500] {standard_task_runner.py:57} INFO - Started process 75134 to run task
[2023-12-13T23:11:04.818+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'manual__2023-12-13T18:05:47.230503+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmp73gnn8nm']
[2023-12-13T23:11:04.821+0500] {standard_task_runner.py:85} INFO - Job 4: Subtask get_data
[2023-12-13T23:11:05.097+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.get_data manual__2023-12-13T18:05:47.230503+00:00 [running]> on host ml-vb
[2023-12-13T23:11:05.582+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-13T18:05:47.230503+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-13T18:05:47.230503+00:00'
[2023-12-13T23:11:05.587+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-13T23:11:05.591+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/akashy/staidg/scripts/get_data.py']
[2023-12-13T23:11:05.619+0500] {subprocess.py:86} INFO - Output:
[2023-12-13T23:11:05.730+0500] {subprocess.py:93} INFO - python3: can't open file '/home/akashy/staidg/scripts/get_data.py': [Errno 2] No such file or directory
[2023-12-13T23:11:05.743+0500] {subprocess.py:97} INFO - Command exited with return code 2
[2023-12-13T23:11:05.842+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ml/project/flow/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-12-13T23:11:05.876+0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=youtube_comments_score, task_id=get_data, execution_date=20231213T180547, start_date=20231213T181104, end_date=20231213T181105
[2023-12-13T23:11:05.930+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task get_data (Bash command failed. The command returned a non-zero exit code 2.; 75134)
[2023-12-13T23:11:05.961+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-13T23:11:06.164+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
