[2023-12-14T23:05:27.588+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2023-12-14T17:51:30.656405+00:00 [queued]>
[2023-12-14T23:05:27.606+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2023-12-14T17:51:30.656405+00:00 [queued]>
[2023-12-14T23:05:27.607+0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-14T23:05:27.636+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_model> on 2023-12-14 17:51:30.656405+00:00
[2023-12-14T23:05:27.647+0500] {standard_task_runner.py:57} INFO - Started process 41489 to run task
[2023-12-14T23:05:27.657+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'train_model', 'manual__2023-12-14T17:51:30.656405+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpghu0gi6u']
[2023-12-14T23:05:27.662+0500] {standard_task_runner.py:85} INFO - Job 88: Subtask train_model
[2023-12-14T23:05:27.984+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.train_model manual__2023-12-14T17:51:30.656405+00:00 [running]> on host ml-vb
[2023-12-14T23:05:28.386+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2023-12-14T17:51:30.656405+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-14T17:51:30.656405+00:00'
[2023-12-14T23:05:28.390+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-14T23:05:28.391+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/ml/project/flow/scripts/train_model.py']
[2023-12-14T23:05:28.410+0500] {subprocess.py:86} INFO - Output:
[2023-12-14T23:06:34.629+0500] {subprocess.py:93} INFO - Registered model 'lr' already exists. Creating a new version of this model...
[2023-12-14T23:06:34.667+0500] {subprocess.py:93} INFO - 2023/12/14 23:06:34 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lr, version 17
[2023-12-14T23:06:35.027+0500] {subprocess.py:93} INFO - Created version '17' of model 'lr'.
[2023-12-14T23:06:35.146+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-14T23:06:35.146+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/scripts/train_model.py", line 27, in <module>
[2023-12-14T23:06:35.146+0500] {subprocess.py:93} INFO -     model.fit(X.values, y.values)
[2023-12-14T23:06:35.147+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/env/lib/python3.8/site-packages/sklearn/base.py", line 1152, in wrapper
[2023-12-14T23:06:35.147+0500] {subprocess.py:93} INFO -     return fit_method(estimator, *args, **kwargs)
[2023-12-14T23:06:35.147+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/env/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 348, in fit
[2023-12-14T23:06:35.147+0500] {subprocess.py:93} INFO -     X, y = self._validate_data(
[2023-12-14T23:06:35.148+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/env/lib/python3.8/site-packages/sklearn/base.py", line 622, in _validate_data
[2023-12-14T23:06:35.148+0500] {subprocess.py:93} INFO -     X, y = check_X_y(X, y, **check_params)
[2023-12-14T23:06:35.148+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/env/lib/python3.8/site-packages/sklearn/utils/validation.py", line 1146, in check_X_y
[2023-12-14T23:06:35.148+0500] {subprocess.py:93} INFO -     X = check_array(
[2023-12-14T23:06:35.149+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/env/lib/python3.8/site-packages/sklearn/utils/validation.py", line 967, in check_array
[2023-12-14T23:06:35.149+0500] {subprocess.py:93} INFO -     raise ValueError(
[2023-12-14T23:06:35.149+0500] {subprocess.py:93} INFO - ValueError: Found array with 0 sample(s) (shape=(0, 5)) while a minimum of 1 is required by RandomForestRegressor.
[2023-12-14T23:06:36.402+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-14T23:06:36.520+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ml/project/flow/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-14T23:06:36.590+0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=youtube_comments_score, task_id=train_model, execution_date=20231214T175130, start_date=20231214T180527, end_date=20231214T180636
[2023-12-14T23:06:36.629+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 88 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 41489)
[2023-12-14T23:06:36.675+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-14T23:06:36.872+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
