[2023-12-14T21:26:56.152+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2023-12-14T16:26:47.763192+00:00 [queued]>
[2023-12-14T21:26:56.177+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2023-12-14T16:26:47.763192+00:00 [queued]>
[2023-12-14T21:26:56.178+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-14T21:26:56.208+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): get_data> on 2023-12-14 16:26:47.763192+00:00
[2023-12-14T21:26:56.216+0500] {standard_task_runner.py:57} INFO - Started process 18986 to run task
[2023-12-14T21:26:56.223+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'manual__2023-12-14T16:26:47.763192+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpn37t_stn']
[2023-12-14T21:26:56.227+0500] {standard_task_runner.py:85} INFO - Job 33: Subtask get_data
[2023-12-14T21:26:56.534+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.get_data manual__2023-12-14T16:26:47.763192+00:00 [running]> on host ml-vb
[2023-12-14T21:26:57.068+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-14T16:26:47.763192+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-14T16:26:47.763192+00:00'
[2023-12-14T21:26:57.074+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-14T21:26:57.076+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/ml/project/flow/scripts/get_data.py']
[2023-12-14T21:26:57.103+0500] {subprocess.py:86} INFO - Output:
[2023-12-14T21:29:56.797+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-14T21:29:56.797+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/scripts/get_data.py", line 36, in <module>
[2023-12-14T21:29:56.797+0500] {subprocess.py:93} INFO -     for item in data['items']:
[2023-12-14T21:29:56.798+0500] {subprocess.py:93} INFO - KeyError: 'items'
[2023-12-14T21:29:57.226+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-14T21:29:57.322+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ml/project/flow/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-14T21:29:57.335+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=get_data, execution_date=20231214T162647, start_date=20231214T162656, end_date=20231214T162957
[2023-12-14T21:29:57.368+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 33 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 18986)
[2023-12-14T21:29:57.423+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-14T21:29:57.535+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
