[2023-12-13T23:50:31.068+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2023-12-13T18:40:24.718875+00:00 [queued]>
[2023-12-13T23:50:31.095+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2023-12-13T18:40:24.718875+00:00 [queued]>
[2023-12-13T23:50:31.095+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-13T23:50:31.121+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_model> on 2023-12-13 18:40:24.718875+00:00
[2023-12-13T23:50:31.133+0500] {standard_task_runner.py:57} INFO - Started process 83018 to run task
[2023-12-13T23:50:31.144+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'train_model', 'manual__2023-12-13T18:40:24.718875+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpjmgf8bx2']
[2023-12-13T23:50:31.147+0500] {standard_task_runner.py:85} INFO - Job 17: Subtask train_model
[2023-12-13T23:50:31.423+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.train_model manual__2023-12-13T18:40:24.718875+00:00 [running]> on host ml-vb
[2023-12-13T23:50:31.940+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2023-12-13T18:40:24.718875+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-13T18:40:24.718875+00:00'
[2023-12-13T23:50:31.944+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-13T23:50:31.945+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/ml/project/flow/scripts/train_model.py']
[2023-12-13T23:50:32.007+0500] {subprocess.py:86} INFO - Output:
[2023-12-13T23:50:59.987+0500] {subprocess.py:93} INFO - Registered model 'lr' already exists. Creating a new version of this model...
[2023-12-13T23:50:59.987+0500] {subprocess.py:93} INFO - 2023/12/13 23:50:59 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lr, version 2
[2023-12-13T23:51:00.419+0500] {subprocess.py:93} INFO - Created version '2' of model 'lr'.
[2023-12-13T23:51:00.420+0500] {subprocess.py:93} INFO - /home/ml/project/flow/env/lib/python3.8/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
[2023-12-13T23:51:00.420+0500] {subprocess.py:93} INFO -   return fit_method(estimator, *args, **kwargs)
[2023-12-13T23:51:00.420+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-13T23:51:00.420+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/scripts/train_model.py", line 29, in <module>
[2023-12-13T23:51:00.421+0500] {subprocess.py:93} INFO -     with open('/home/ml/project/flow/models/data.pickle', 'wb') as f:
[2023-12-13T23:51:00.421+0500] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/home/ml/project/flow/models/data.pickle'
[2023-12-13T23:51:01.071+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-13T23:51:01.164+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ml/project/flow/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-13T23:51:01.171+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=train_model, execution_date=20231213T184024, start_date=20231213T185031, end_date=20231213T185101
[2023-12-13T23:51:01.201+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 83018)
[2023-12-13T23:51:01.252+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-13T23:51:01.357+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
