[2023-12-14T23:10:08.325+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2023-12-14T18:03:25.673475+00:00 [queued]>
[2023-12-14T23:10:08.340+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2023-12-14T18:03:25.673475+00:00 [queued]>
[2023-12-14T23:10:08.341+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-14T23:10:08.414+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_model> on 2023-12-14 18:03:25.673475+00:00
[2023-12-14T23:10:08.424+0500] {standard_task_runner.py:57} INFO - Started process 42820 to run task
[2023-12-14T23:10:08.434+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'train_model', 'manual__2023-12-14T18:03:25.673475+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmp29gc0e0j']
[2023-12-14T23:10:08.437+0500] {standard_task_runner.py:85} INFO - Job 98: Subtask train_model
[2023-12-14T23:10:08.685+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.train_model manual__2023-12-14T18:03:25.673475+00:00 [running]> on host ml-vb
[2023-12-14T23:10:09.136+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2023-12-14T18:03:25.673475+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-14T18:03:25.673475+00:00'
[2023-12-14T23:10:09.139+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-14T23:10:09.140+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/ml/project/flow/scripts/train_model.py']
[2023-12-14T23:10:09.175+0500] {subprocess.py:86} INFO - Output:
[2023-12-14T23:10:40.330+0500] {subprocess.py:93} INFO - Registered model 'lr' already exists. Creating a new version of this model...
[2023-12-14T23:10:40.350+0500] {subprocess.py:93} INFO - 2023/12/14 23:10:40 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lr, version 21
[2023-12-14T23:10:40.403+0500] {subprocess.py:93} INFO - Created version '21' of model 'lr'.
[2023-12-14T23:10:40.449+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-14T23:10:40.449+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/scripts/train_model.py", line 27, in <module>
[2023-12-14T23:10:40.449+0500] {subprocess.py:93} INFO -     model.fit(X.values, y.values)
[2023-12-14T23:10:40.449+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/env/lib/python3.8/site-packages/sklearn/base.py", line 1152, in wrapper
[2023-12-14T23:10:40.450+0500] {subprocess.py:93} INFO -     return fit_method(estimator, *args, **kwargs)
[2023-12-14T23:10:40.450+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/env/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 348, in fit
[2023-12-14T23:10:40.450+0500] {subprocess.py:93} INFO -     X, y = self._validate_data(
[2023-12-14T23:10:40.450+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/env/lib/python3.8/site-packages/sklearn/base.py", line 622, in _validate_data
[2023-12-14T23:10:40.451+0500] {subprocess.py:93} INFO -     X, y = check_X_y(X, y, **check_params)
[2023-12-14T23:10:40.451+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/env/lib/python3.8/site-packages/sklearn/utils/validation.py", line 1146, in check_X_y
[2023-12-14T23:10:40.451+0500] {subprocess.py:93} INFO -     X = check_array(
[2023-12-14T23:10:40.451+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/env/lib/python3.8/site-packages/sklearn/utils/validation.py", line 967, in check_array
[2023-12-14T23:10:40.451+0500] {subprocess.py:93} INFO -     raise ValueError(
[2023-12-14T23:10:40.452+0500] {subprocess.py:93} INFO - ValueError: Found array with 0 sample(s) (shape=(0, 5)) while a minimum of 1 is required by RandomForestRegressor.
[2023-12-14T23:10:41.085+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-14T23:10:41.192+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ml/project/flow/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-14T23:10:41.217+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=train_model, execution_date=20231214T180325, start_date=20231214T181008, end_date=20231214T181041
[2023-12-14T23:10:41.241+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 98 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 42820)
[2023-12-14T23:10:41.267+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-14T23:10:41.354+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
