[2023-12-14T21:13:15.450+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2023-12-14T16:13:05.113932+00:00 [queued]>
[2023-12-14T21:13:15.468+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2023-12-14T16:13:05.113932+00:00 [queued]>
[2023-12-14T21:13:15.468+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-14T21:13:15.499+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): get_data> on 2023-12-14 16:13:05.113932+00:00
[2023-12-14T21:13:15.513+0500] {standard_task_runner.py:57} INFO - Started process 16312 to run task
[2023-12-14T21:13:15.519+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'manual__2023-12-14T16:13:05.113932+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmp3plnqvyh']
[2023-12-14T21:13:15.524+0500] {standard_task_runner.py:85} INFO - Job 29: Subtask get_data
[2023-12-14T21:13:15.915+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.get_data manual__2023-12-14T16:13:05.113932+00:00 [running]> on host ml-vb
[2023-12-14T21:13:16.551+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-14T16:13:05.113932+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-14T16:13:05.113932+00:00'
[2023-12-14T21:13:16.556+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-14T21:13:16.557+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/ml/project/flow/scripts/get_data.py']
[2023-12-14T21:13:16.668+0500] {subprocess.py:86} INFO - Output:
[2023-12-14T21:13:53.886+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-14T21:13:53.887+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/scripts/get_data.py", line 36, in <module>
[2023-12-14T21:13:53.887+0500] {subprocess.py:93} INFO -     for item in data['items']:
[2023-12-14T21:13:53.887+0500] {subprocess.py:93} INFO - KeyError: 'items'
[2023-12-14T21:13:54.237+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-14T21:13:54.320+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ml/project/flow/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-14T21:13:54.339+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=get_data, execution_date=20231214T161305, start_date=20231214T161315, end_date=20231214T161354
[2023-12-14T21:13:54.499+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 29 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 16312)
[2023-12-14T21:13:54.549+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-14T21:13:54.685+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
